trainingInput:
    scaleTier: BASIC_GPU

    pythonVersion: '3.5'
    runtimeVersion: '1.8'
    region: 'europe-west1'
    pythonModule: 'tf_crnn.task'
    jobDir: 'gs://hwr-data/models/hwr1/'

    args:
      - '--learning-rate=0.001'
      - '--learning-rate-decay=0.95'
      - '--learning-rate-steps=5000'
